# This file contains values from Cookiecutter

default_context:
  project_name: "aws-service-availability"
  project_description: "CLI tool for listing (un)available AWS services by region"
  organization: "JensRoland"
  license: "GNU GPL v3.0"
  python_version: 3.7
  github_username: "jensroland"
  email: "mail@jensroland.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "cli"
